Increment7
EestiChameleon/URLShortenerService pull request #8
Opened 2022-02-24 14:48 UTC by EestiChameleon

flag parsing

2022-02-28 17:41 UTC, Barugoo commented on cmd/shortener/main.go
> +}
Давай этот код перенесем в начало функции `main`
Лучше не использовать `init` без необходимости, они усложняют код

2022-02-28 17:41 UTC, Barugoo commented on cmd/shortener/main.go
> +		panic(err)
Давай лучше `log.Fatal`
Паника немного для другого

2022-02-28 17:42 UTC, Barugoo commented on internal/app/cfg/config.go
> +		log.Fatal(err)
Давай не прибивать процесс где-то за пределами функции `main`
Потом замучаешься искать, где в коде у тебя процесс фаталит

2022-02-28 17:46 UTC, Barugoo commented on internal/app/handlers/post_json.go
> +	}
Можно еще сделать так:
```go
var reqBody ReqBody

if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
    log.Println("unable to parse body:", err)
    resp.WriteString(w, http.StatusBadRequest, "invalid data")
    return
}
```

2022-02-28 17:47 UTC, Barugoo commented on internal/app/handlers/post_json.go
> +	if !strings.Contains(r.Header.Get(resp.HeaderContentType), resp.MIMEApplicationJSON) {
Давай не инлайнить здесь:
```go
contentType := r.Header.Get(resp.HeaderContentType)
if !strings.Contains(contentType, resp.MIMEApplicationJSON) {
```

2022-02-28 17:49 UTC, Barugoo commented on internal/app/responses/templates.go
> +//}
Давай не держать закомментированный код в репе. Не используется - удаляем

2022-02-28 17:49 UTC, Barugoo commented on internal/app/responses/templates.go
> +const (
Нам точно нужно объявлять здесь все константы, даже те, которые никак не испоьзуются в коде?

2022-02-28 17:52 UTC, Barugoo commented on internal/app/responses/templates.go
> +	if err != nil {
Проверять ошибку здесь смысла нет: если ты не можешь записать байтики в подключение, то ответ со статусом вернуть тоже не сможешь, тк соединение уже вероятно разорвано)

2022-02-28 18:06 UTC, Barugoo commented on internal/app/storage/database.go
> +func (d *data) CreateDir() error {
А нам действительно нужна эта функция? Мы же можем просто ручками один раз в репозитории создать директорию

2022-02-28 18:07 UTC, Barugoo commented on internal/app/storage/database.go
> +	_, err := d.File.WriteString(shortURL + " : " + longURL + "\n")
А что делать, если мы хотим удалить существующий шорт урл? Как его искать?

2022-02-28 18:08 UTC, Barugoo commented on internal/app/storage/database.go
> +	_, err := d.File.WriteString(shortURL + " : " + longURL + "\n")
Давай мы будем сохранять данные в каком-то текстовом формате, например в JSON'е
Будем парсить его в мапку и с мапкой уже работать. Если захотим скинуть данные из памяти на диск - мапку сериализуем и перезаписываем содержимое файла.

2022-02-28 18:09 UTC, Barugoo requested changes
Хорошо, но есть замечания
go vet test валится

2022-03-01 11:04 UTC, EestiChameleon commented
Ошибки исправлены

2022-03-02 12:58 UTC, Barugoo commented on internal/app/storage/database.go
> +	//}
Давай удалять закоменченный код из репы, надо будет вернуть - все есть в гите

2022-03-02 12:58 UTC, Barugoo approved these changes
Отлично!

2022-03-04 08:18 UTC, merged